wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
layer_size:
  value: 32
learning_rate:
  value: 0.001
num_epochs:
  value: 5
num_layers:
  value: 5
optimizer:
  value: nesterov
weight_decay:
  value: 0
weight_init:
  value: random
