wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
layer_size:
  value: 64
learning_rate:
  value: 0.001
num_epochs:
  value: 10
num_layers:
  value: 4
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
