wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      4: 3.8.5
      5: 0.10.21
      8:
      - 1
      - 3
      - 5
batch_normalize:
  desc: null
  value: false
data_augment:
  desc: null
  value: false
dropout:
  desc: null
  value: 0
filter_factor:
  desc: null
  value: 1
n_filters:
  desc: null
  value: 10
