wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
layer_size:
  value: 32
learning_rate:
  value: 0.001
num_epochs:
  value: 10
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
