wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.8.5
      5: 0.10.21
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 64
layer_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.01
num_epochs:
  desc: null
  value: 10
num_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: rmsprop
weight_decay:
  desc: null
  value: 0.0005
weight_init:
  desc: null
  value: random
