wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      4: 3.8.5
      5: 0.10.21
      8:
      - 1
      - 3
      - 5
cell type:
  desc: null
  value: GRU
cell_type:
  desc: null
  value: RNN
dropout:
  desc: null
  value: 0.2
hidden_layer_size:
  desc: null
  value: 256
num_decoders:
  desc: null
  value: 2
num_encoders:
  desc: null
  value: 3
num_epochs:
  desc: null
  value: 30
