wandb_version: 1

batch_normalize:
  value: false
data_augment:
  value: false
dropout:
  value: 0.4
filter_size:
  value: 3
filter_size_decay:
  value: 1
n_dense:
  value: 100
n_filters:
  value: 32
