wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
layer_size:
  value: 32
learning_rate:
  value: 0.001
num_epochs:
  value: 10
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
