wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
layer_size:
  value: 128
learning_rate:
  value: 0.01
num_epochs:
  value: 10
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
