wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
layer_size:
  value: 128
learning_rate:
  value: 0.01
num_epochs:
  value: 5
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
