wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
layer_size:
  value: 128
learning_rate:
  value: 0.01
num_epochs:
  value: 10
num_layers:
  value: 5
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: random
