wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
layer_size:
  value: 128
learning_rate:
  value: 0.01
num_epochs:
  value: 5
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
