wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_epochs:
  value: 5
num_layers:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: random
