wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_epochs:
  value: 10
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: random
