wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
layer_size:
  value: 32
learning_rate:
  value: 0.01
num_epochs:
  value: 10
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
