wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
layer_size:
  value: 128
learning_rate:
  value: 0.001
num_epochs:
  value: 10
num_layers:
  value: 5
optimizer:
  value: normal
weight_decay:
  value: 0
weight_init:
  value: Xavier
